### ISSUE TITLE
Add /sparql route as proxy

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/rialto-api#18]
Add a oute of `/sparql` that is just a http proxy (with messaging attached still to the response) to a configured internal sparql endpoint (for us, neptune)

**Comment by cmh2166** [comment]
should support passing through any request to that `/sparql` endpoint, including update or query, and returning received error response in case that configured triplestore sparql endpoint doesn't support that request type. should also include messaging to sns.

**Comment by jcoyne** [comment]
May I suggest that the sns message for this endpoint uses a different `action` than the message sent by the json endpoint.  That way we can distinguish between a partial index rebuild and a full-index rebuild.  Also, maybe we only need to send a message on  an INSERT or DELETE.
