### ISSUE TITLE
Document allowed / protected queries on sparql proxy endpoint

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/rialto-api#24]
Should we block DELETE on the proxy? Should we limit update/insert?

**Comment by jcoyne** [comment]
SPARQL doesn't really have "UPDATE" it only has a combination DELETE/INSERT, right?

**Comment by aaron-collier** [comment]
SPARQL over http does support PATCH (per the spec: https://www.w3.org/TR/2013/REC-sparql11-http-rdf-update-20130321/#http-patch) which they describe as update.
