### ISSUE TITLE
Extract messageWriter from storageWriter

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/rialto-api#25]
Currently, the messageWriter is only available in the storage writer. It should be available to other methods for sending messages that do not utilize the storage writer.

**Comment by jcoyne** [comment]
@aaron-collier I don't understand this ticket. There is https://github.com/sul-dlss-labs/rialto-api/blob/master/services/message_service.go which is not part of the storage writer. Can you state this in a different way?

**Comment by aaron-collier** [comment]
@jcoyne Ah, thanks. I was reading injection of the storage writer incorrectly as I would need to pass a message through it, but I see that I can use the messagerService indendently. Thanks :-) will close this.
